## VALD
VALD is a database of atomic and molecular transitions used to create accurate synthetic spectra of many astrophysical systems. More information, as well as linelists can be downloaded from the [VALD website](http://vald.astro.uu.se/~vald/php/vald.ph).

In this example, data was downloaded from the [VALD website](http://vald.astro.uu.se/) and extracted to /tmp/vald_sample_linelist.dat

**_NOTE:_**

In [1]:
from carsus.io.vald import VALDReader

In [2]:
vald_reader = VALDReader(fname='/tmp/vald_sample_linelist.dat')

Table information is parsed to a dataframe which can be accesed via the .vald attribute. The column information is described in https://articles.adsabs.harvard.edu/pdf/1995A%26AS..112..525P and is as follows:

Wavelength - either air or vacuum and in nanometers or angstroms: Wavelength of the line

log_gf: Log10 of the oscillator strength times the degeneracy of the lower level

e_low: Excitation energy of the lower level in ergs

j_lo: Principal quantum number of the lower level

e_up: Excitation energy of the upper level in ergs

j_up: Principal quantum number of the upper level

lande_lower: Lande factor of the lower level

lande_upper: Lande factor of the upper level

lande_mean: Mean lande factor

rad: log10 of the radiation damping constant in $(4\pi s)^{-1}$

stark: log10 of the Stark damping constant at 10,000K in $(4\pi s N_e)^{-1}$

waals: log10 of the Van Der Waals damping constant at 10,000K in $(4\pi s N_H)^{-1}$

In [3]:
vald_reader.vald

[        carsus.io.vald.vald][   INFO] - Parsing VALD from: /tmp/vald_sample_linelist.dat (vald.py:149)
[        carsus.io.vald.vald][   INFO] - Found wavelength column header: WL_air(A) (vald.py:167)

,WL_air(A),log_gf,e_low,j_lo,e_up,j_up,lande_lower,lande_upper,lande_mean,rad,stark,waals,chemical,ion_charge,wavelength,atomic_number
0,4100.00538,-1.169,8.1293,2.0,11.1524,3.0,1.04,1.00,0.96,8.70,-6.47,-7.860,Mn,1,4101.162586,25
1,4100.04321,-5.992,10.4673,1.5,13.4904,2.5,2.28,1.54,0.99,8.94,-5.86,-7.630,Fe,1,4101.200426,26
2,4100.04405,-0.440,16.8273,2.0,19.8504,1.0,1.40,1.48,1.36,9.48,-5.99,-7.710,Ti,2,4101.201266,22
3,4100.04800,-0.725,51.0168,3.5,54.0399,4.5,99.00,99.00,99.00,10.00,0.00,0.000,He,1,4101.205217,2
4,4100.04910,-7.287,15.2375,2.0,18.2606,1.0,1.47,3.00,0.71,9.47,-6.35,-7.850,Fe,2,4101.206318,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,4109.94851,-5.428,3.8470,2.0,6.8628,3.0,1.16,0.95,0.75,8.10,-6.16,-7.750,Cr,0,4111.108321,24
991,4109.94900,-1.227,10.6900,1.5,13.7058,2.5,99.00,99.00,99.00,0.00,0.00,-7.419,N,0,4111.108811,7
992,4109.95324,-2.671,4.6244,2.0,7.6402,1.0,1.00,0.83,1.08,7.47,-2.75,-6.710,Ca,0,4111.113052,20
993,4109.96777,-4.848,13.9360,5.0,16.9518,5.0,1.38,1.20,1.29,8.44,-5.18,-7.500,Cu,1,4111.127586,29
994,4109.98163,-3.441,4.5351,4.0,7.5509,3.0,1.07,1.25,0.79,7.61,-4.43,-7.320,Cr,0,4111.141449,24

The specific relevant information is extracted and prepared as a linelist in the .linelist attribute.

Note that the wavelengths here are reformated to Angstroms and in vacuum wavelengths.

In [4]:
vald_reader.linelist

,atomic_number,ion_charge,wavelength,log_gf,e_low,e_up,j_lo,j_up,rad,stark,waals
0,25,1,4101.162586,-1.169,8.1293,11.1524,2.0,3.0,8.70,-6.47,-7.860
1,26,1,4101.200426,-5.992,10.4673,13.4904,1.5,2.5,8.94,-5.86,-7.630
2,22,2,4101.201266,-0.440,16.8273,19.8504,2.0,1.0,9.48,-5.99,-7.710
3,2,1,4101.205217,-0.725,51.0168,54.0399,3.5,4.5,10.00,0.00,0.000
4,26,2,4101.206318,-7.287,15.2375,18.2606,2.0,1.0,9.47,-6.35,-7.850
...,...,...,...,...,...,...,...,...,...,...,...
990,24,0,4111.108321,-5.428,3.8470,6.8628,2.0,3.0,8.10,-6.16,-7.750
991,7,0,4111.108811,-1.227,10.6900,13.7058,1.5,2.5,0.00,0.00,-7.419
992,20,0,4111.113052,-2.671,4.6244,7.6402,2.0,1.0,7.47,-2.75,-6.710
993,29,1,4111.127586,-4.848,13.9360,16.9518,5.0,5.0,8.44,-5.18,-7.500
994,24,0,4111.141449,-3.441,4.5351,7.5509,4.0,3.0,7.61,-4.43,-7.320